package com.neobe.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class cliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CLIENTE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "CLIENTE_ID_SEQ", name = "CLIENTE_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Nome")
	private java.lang.String nome;

	@org.kie.api.definition.type.Label("RG")
	private java.lang.String rg;

	@org.kie.api.definition.type.Label(value = "CPF")
	private java.lang.String cpf;

	public cliente() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.String getRg() {
		return this.rg;
	}

	public void setRg(java.lang.String rg) {
		this.rg = rg;
	}

	public java.lang.String getCpf() {
		return this.cpf;
	}

	public void setCpf(java.lang.String cpf) {
		this.cpf = cpf;
	}

	public cliente(java.lang.Long id, java.lang.String nome,
			java.lang.String rg, java.lang.String cpf) {
		this.id = id;
		this.nome = nome;
		this.rg = rg;
		this.cpf = cpf;
	}

}