package com.neobe.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class controle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Sla do processo")
	private java.lang.String sla;

	@org.kie.api.definition.type.Label("Grupo de usuarios")
	private java.lang.String grupo;

	@org.kie.api.definition.type.Label("Usuário padrão")
	private java.lang.String usuario;

	@org.kie.api.definition.type.Label("Negativas cadastrais?")
	private java.lang.Boolean negativascadastrais;

	@org.kie.api.definition.type.Label("Exceção")
	private String excecao;

	@org.kie.api.definition.type.Label(value = "Urgência emergência confirmada")
	private java.lang.Boolean urg_emerg_confirmada;

	public controle() {
	}

	public java.lang.String getSla() {
		return this.sla;
	}

	public void setSla(java.lang.String sla) {
		this.sla = sla;
	}

	public java.lang.String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(java.lang.String grupo) {
		this.grupo = grupo;
	}

	public java.lang.String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(java.lang.String usuario) {
		this.usuario = usuario;
	}

	public java.lang.Boolean getNegativascadastrais() {
		return this.negativascadastrais;
	}

	public void setNegativascadastrais(java.lang.Boolean negativascadastrais) {
		this.negativascadastrais = negativascadastrais;
	}

	public java.lang.String getExcecao() {
		return this.excecao;
	}

	public void setExcecao(java.lang.String excecao) {
		this.excecao = excecao;
	}

	public java.lang.Boolean getUrg_emerg_confirmada() {
		return this.urg_emerg_confirmada;
	}

	public void setUrg_emerg_confirmada(java.lang.Boolean urg_emerg_confirmada) {
		this.urg_emerg_confirmada = urg_emerg_confirmada;
	}

	public controle(java.lang.String sla, java.lang.String grupo,
			java.lang.String usuario, java.lang.Boolean negativascadastrais,
			java.lang.String excecao, java.lang.Boolean urg_emerg_confirmada) {
		this.sla = sla;
		this.grupo = grupo;
		this.usuario = usuario;
		this.negativascadastrais = negativascadastrais;
		this.excecao = excecao;
		this.urg_emerg_confirmada = urg_emerg_confirmada;
	}

}