package com.neobe.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Empresa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EMPRESA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "EMPRESA_ID_SEQ", name = "EMPRESA_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Nome")
	private java.lang.String nome;

	public Empresa() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public Empresa(java.lang.Long id, java.lang.String nome) {
		this.id = id;
		this.nome = nome;
	}

}