package com.neobe.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class solicitacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SOLICITACAO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SOLICITACAO_ID_SEQ", name = "SOLICITACAO_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Nome do beneficiario")
	private java.lang.String beneficiario_nome;

	@org.kie.api.definition.type.Label("Idade")
	private java.lang.Integer beneficiario_idade;

	@org.kie.api.definition.type.Label("Operadora")
	private java.lang.String operadora_nome;

	@org.kie.api.definition.type.Label("Situacao da solicitacao")
	private java.lang.String situacao_original;

	@org.kie.api.definition.type.Label("Situacao pos regulacao")
	private java.lang.String situacao_regulacao;

	@org.kie.api.definition.type.Label("Documentacao ok?")
	@org.kie.api.definition.type.Description("descricoao")
	private java.lang.Boolean documentacao_ok;

	@org.kie.api.definition.type.Label("Necessario doc adicional?")
	private java.lang.Boolean documentacao_adicional;

	@org.kie.api.definition.type.Label("Negativas de prestador?")
	private java.lang.Boolean negativas_prestador;

	@org.kie.api.definition.type.Label("Negativas de beneficiario?")
	private java.lang.Boolean negativas_beneficiario;

	@org.kie.api.definition.type.Label("Negativas de evento?")
	private java.lang.Boolean negativas_evento;

	@org.kie.api.definition.type.Label("Evento com DUT ou ROL?")
	private java.lang.Boolean evento_com_dut_ou_rol;

	@org.kie.api.definition.type.Label("Tipo da solicitacao")
	private java.lang.String solicitacao_tipo;

	@org.kie.api.definition.type.Label("Tipo do SADT")
	private java.lang.String sadt_tipo;

	@org.kie.api.definition.type.Label("Subtipo do SADT")
	private java.lang.String sadt_subtipo;

	@org.kie.api.definition.type.Label("Parecer do medico?")
	private java.lang.String parecer_medico;

	@org.kie.api.definition.type.Label("Parecer administrativo / enfermeiro")
	private java.lang.String parecer_adm_enf;

	@org.kie.api.definition.type.Label("O limite foi ultrapassado?")
	private java.lang.Boolean limite_ultrapassado;

	@org.kie.api.definition.type.Label("Realizado contato com solicitante?")
	private String contato_com_solicitante_realizado;

	@org.kie.api.definition.type.Label("Parecer da operadora sobre negativas de prest e benef")
	private java.lang.String operadora_parecer_negativas;

	@javax.annotation.Generated({"org.optaplanner.workbench.screens.domaineditor.client.widgets.planner.PlannerDataObjectEditor"})
	@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(org.optaplanner.persistence.jaxb.api.score.buildin.hardsoft.HardSoftScoreJaxbXmlAdapter.class)
	@org.kie.api.definition.type.Label("Generated Planner score field")
	@org.optaplanner.core.api.domain.solution.PlanningScore
	private org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score;

	@org.kie.api.definition.type.Label("Observações")
	private java.lang.String obs;

	@org.kie.api.definition.type.Label("Prestador fora do domicilio?")
	private java.lang.Boolean prestador_fora_domicilio;

	@org.kie.api.definition.type.Label("Urgência/Emergência")
	private java.lang.Boolean urgencia_emergencia;

	@org.kie.api.definition.type.Label("Negativas revertidas")
	private java.lang.Boolean operadora_negativas_revertidas;

	@org.kie.api.definition.type.Label("A solicitação exige documentação")
	private java.lang.Boolean documentacao_exigida;

	@org.kie.api.definition.type.Label("Solicitação é oncológica")
	private java.lang.Boolean eh_oncologica;

	@org.kie.api.definition.type.Label(value = "Solicitação possui OPME?")
	private java.lang.Boolean possui_opme;

	public solicitacao() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getBeneficiario_nome() {
		return this.beneficiario_nome;
	}

	public void setBeneficiario_nome(java.lang.String beneficiario_nome) {
		this.beneficiario_nome = beneficiario_nome;
	}

	public java.lang.Integer getBeneficiario_idade() {
		return this.beneficiario_idade;
	}

	public void setBeneficiario_idade(java.lang.Integer beneficiario_idade) {
		this.beneficiario_idade = beneficiario_idade;
	}

	public java.lang.String getOperadora_nome() {
		return this.operadora_nome;
	}

	public void setOperadora_nome(java.lang.String operadora_nome) {
		this.operadora_nome = operadora_nome;
	}

	public java.lang.String getSituacao_original() {
		return this.situacao_original;
	}

	public void setSituacao_original(java.lang.String situacao_original) {
		this.situacao_original = situacao_original;
	}

	public java.lang.String getSituacao_regulacao() {
		return this.situacao_regulacao;
	}

	public void setSituacao_regulacao(java.lang.String situacao_regulacao) {
		this.situacao_regulacao = situacao_regulacao;
	}

	public java.lang.Boolean getDocumentacao_ok() {
		return this.documentacao_ok;
	}

	public void setDocumentacao_ok(java.lang.Boolean documentacao_ok) {
		this.documentacao_ok = documentacao_ok;
	}

	public java.lang.Boolean getDocumentacao_adicional() {
		return this.documentacao_adicional;
	}

	public void setDocumentacao_adicional(
			java.lang.Boolean documentacao_adicional) {
		this.documentacao_adicional = documentacao_adicional;
	}

	public java.lang.Boolean getNegativas_prestador() {
		return this.negativas_prestador;
	}

	public void setNegativas_prestador(java.lang.Boolean negativas_prestador) {
		this.negativas_prestador = negativas_prestador;
	}

	public java.lang.Boolean getNegativas_beneficiario() {
		return this.negativas_beneficiario;
	}

	public void setNegativas_beneficiario(
			java.lang.Boolean negativas_beneficiario) {
		this.negativas_beneficiario = negativas_beneficiario;
	}

	public java.lang.Boolean getNegativas_evento() {
		return this.negativas_evento;
	}

	public void setNegativas_evento(java.lang.Boolean negativas_evento) {
		this.negativas_evento = negativas_evento;
	}

	public java.lang.Boolean getEvento_com_dut_ou_rol() {
		return this.evento_com_dut_ou_rol;
	}

	public void setEvento_com_dut_ou_rol(java.lang.Boolean evento_com_dut_ou_rol) {
		this.evento_com_dut_ou_rol = evento_com_dut_ou_rol;
	}

	public java.lang.String getSolicitacao_tipo() {
		return this.solicitacao_tipo;
	}

	public void setSolicitacao_tipo(java.lang.String solicitacao_tipo) {
		this.solicitacao_tipo = solicitacao_tipo;
	}

	public java.lang.String getSadt_tipo() {
		return this.sadt_tipo;
	}

	public void setSadt_tipo(java.lang.String sadt_tipo) {
		this.sadt_tipo = sadt_tipo;
	}

	public java.lang.String getSadt_subtipo() {
		return this.sadt_subtipo;
	}

	public void setSadt_subtipo(java.lang.String sadt_subtipo) {
		this.sadt_subtipo = sadt_subtipo;
	}

	public java.lang.String getParecer_medico() {
		return this.parecer_medico;
	}

	public void setParecer_medico(java.lang.String parecer_medico) {
		this.parecer_medico = parecer_medico;
	}

	public java.lang.String getParecer_adm_enf() {
		return this.parecer_adm_enf;
	}

	public void setParecer_adm_enf(java.lang.String parecer_adm_enf) {
		this.parecer_adm_enf = parecer_adm_enf;
	}

	public java.lang.Boolean getLimite_ultrapassado() {
		return this.limite_ultrapassado;
	}

	public void setLimite_ultrapassado(java.lang.Boolean limite_ultrapassado) {
		this.limite_ultrapassado = limite_ultrapassado;
	}

	public java.lang.String getContato_com_solicitante_realizado() {
		return this.contato_com_solicitante_realizado;
	}

	public void setContato_com_solicitante_realizado(
			java.lang.String contato_com_solicitante_realizado) {
		this.contato_com_solicitante_realizado = contato_com_solicitante_realizado;
	}

	public java.lang.String getOperadora_parecer_negativas() {
		return this.operadora_parecer_negativas;
	}

	public void setOperadora_parecer_negativas(
			java.lang.String operadora_parecer_negativas) {
		this.operadora_parecer_negativas = operadora_parecer_negativas;
	}

	public org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore getScore() {
		return this.score;
	}

	public void setScore(
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score) {
		this.score = score;
	}

	public java.lang.String getObs() {
		return this.obs;
	}

	public void setObs(java.lang.String obs) {
		this.obs = obs;
	}

	public java.lang.Boolean getPrestador_fora_domicilio() {
		return this.prestador_fora_domicilio;
	}

	public void setPrestador_fora_domicilio(
			java.lang.Boolean prestador_fora_domicilio) {
		this.prestador_fora_domicilio = prestador_fora_domicilio;
	}

	public java.lang.Boolean getUrgencia_emergencia() {
		return this.urgencia_emergencia;
	}

	public void setUrgencia_emergencia(java.lang.Boolean urgencia_emergencia) {
		this.urgencia_emergencia = urgencia_emergencia;
	}

	public java.lang.Boolean getOperadora_negativas_revertidas() {
		return this.operadora_negativas_revertidas;
	}

	public void setOperadora_negativas_revertidas(
			java.lang.Boolean operadora_negativas_revertidas) {
		this.operadora_negativas_revertidas = operadora_negativas_revertidas;
	}

	public java.lang.Boolean getDocumentacao_exigida() {
		return this.documentacao_exigida;
	}

	public void setDocumentacao_exigida(java.lang.Boolean documentacao_exigida) {
		this.documentacao_exigida = documentacao_exigida;
	}

	public java.lang.Boolean getEh_oncologica() {
		return this.eh_oncologica;
	}

	public void setEh_oncologica(java.lang.Boolean eh_oncologica) {
		this.eh_oncologica = eh_oncologica;
	}

	public java.lang.Boolean getPossui_opme() {
		return this.possui_opme;
	}

	public void setPossui_opme(java.lang.Boolean possui_opme) {
		this.possui_opme = possui_opme;
	}

	public solicitacao(
			java.lang.Long id,
			java.lang.String beneficiario_nome,
			java.lang.Integer beneficiario_idade,
			java.lang.String operadora_nome,
			java.lang.String situacao_original,
			java.lang.String situacao_regulacao,
			java.lang.Boolean documentacao_ok,
			java.lang.Boolean documentacao_adicional,
			java.lang.Boolean negativas_prestador,
			java.lang.Boolean negativas_beneficiario,
			java.lang.Boolean negativas_evento,
			java.lang.Boolean evento_com_dut_ou_rol,
			java.lang.String solicitacao_tipo,
			java.lang.String sadt_tipo,
			java.lang.String sadt_subtipo,
			java.lang.String parecer_medico,
			java.lang.String parecer_adm_enf,
			java.lang.Boolean limite_ultrapassado,
			java.lang.String contato_com_solicitante_realizado,
			java.lang.String operadora_parecer_negativas,
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score,
			java.lang.String obs, java.lang.Boolean prestador_fora_domicilio,
			java.lang.Boolean urgencia_emergencia,
			java.lang.Boolean operadora_negativas_revertidas,
			java.lang.Boolean documentacao_exigida,
			java.lang.Boolean eh_oncologica, java.lang.Boolean possui_opme) {
		this.id = id;
		this.beneficiario_nome = beneficiario_nome;
		this.beneficiario_idade = beneficiario_idade;
		this.operadora_nome = operadora_nome;
		this.situacao_original = situacao_original;
		this.situacao_regulacao = situacao_regulacao;
		this.documentacao_ok = documentacao_ok;
		this.documentacao_adicional = documentacao_adicional;
		this.negativas_prestador = negativas_prestador;
		this.negativas_beneficiario = negativas_beneficiario;
		this.negativas_evento = negativas_evento;
		this.evento_com_dut_ou_rol = evento_com_dut_ou_rol;
		this.solicitacao_tipo = solicitacao_tipo;
		this.sadt_tipo = sadt_tipo;
		this.sadt_subtipo = sadt_subtipo;
		this.parecer_medico = parecer_medico;
		this.parecer_adm_enf = parecer_adm_enf;
		this.limite_ultrapassado = limite_ultrapassado;
		this.contato_com_solicitante_realizado = contato_com_solicitante_realizado;
		this.operadora_parecer_negativas = operadora_parecer_negativas;
		this.score = score;
		this.obs = obs;
		this.prestador_fora_domicilio = prestador_fora_domicilio;
		this.urgencia_emergencia = urgencia_emergencia;
		this.operadora_negativas_revertidas = operadora_negativas_revertidas;
		this.documentacao_exigida = documentacao_exigida;
		this.eh_oncologica = eh_oncologica;
		this.possui_opme = possui_opme;
	}

}