package com.neobe.regulacao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Titular implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TITULAR_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "TITULAR_ID_SEQ", name = "TITULAR_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Nome")
	private java.lang.String nome;

	@org.kie.api.definition.type.Label("RG")
	private java.lang.String rg;

	@org.kie.api.definition.type.Label("Cancelado?")
	private java.lang.Boolean cancelado;

	@org.kie.api.definition.type.Label("Nascimento")
	private java.util.Date dtNascimento;

	@org.kie.api.definition.type.Label("SobreNome")
	private java.lang.String sobrenome;

	@org.kie.api.definition.type.Label(value = "Tit eleitos")
	private java.lang.String tituloeleitor;

	public Titular() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.String getRg() {
		return this.rg;
	}

	public void setRg(java.lang.String rg) {
		this.rg = rg;
	}

	public java.lang.Boolean getCancelado() {
		return this.cancelado;
	}

	public void setCancelado(java.lang.Boolean cancelado) {
		this.cancelado = cancelado;
	}

	public java.util.Date getDtNascimento() {
		return this.dtNascimento;
	}

	public void setDtNascimento(java.util.Date dtNascimento) {
		this.dtNascimento = dtNascimento;
	}

	public java.lang.String getSobrenome() {
		return this.sobrenome;
	}

	public void setSobrenome(java.lang.String sobrenome) {
		this.sobrenome = sobrenome;
	}

	public java.lang.String getTituloeleitor() {
		return this.tituloeleitor;
	}

	public void setTituloeleitor(java.lang.String tituloeleitor) {
		this.tituloeleitor = tituloeleitor;
	}

	public Titular(java.lang.Long id, java.lang.String nome,
			java.lang.String rg, java.lang.Boolean cancelado,
			java.util.Date dtNascimento, java.lang.String sobrenome,
			java.lang.String tituloeleitor) {
		this.id = id;
		this.nome = nome;
		this.rg = rg;
		this.cancelado = cancelado;
		this.dtNascimento = dtNascimento;
		this.sobrenome = sobrenome;
		this.tituloeleitor = tituloeleitor;
	}

}